namespace CacheOrchestrator.AdminConsole.Services.Hints.Declarative;

/// <summary>Allowlisted paths for declarative rules (compiler checks these).</summary>
public static class HintPathCatalog
{
    private static readonly HashSet<string> Paths = new(StringComparer.OrdinalIgnoreCase)
    {
        "domain.requests",
        "domain.invalidations",
        "domain.invalidationShare",
        "domain.version",
        "domain.versionIsRuntimeOverride",
        "domain.schedulePhase",
        "domain.hasSchedule",
        "domain.factoryFailureRate",
        "domain.outputCache.hitShare",
        "domain.outputCache.hits",
        "domain.outputCache.misses",
        "domain.dataCache.hitShare",
        "domain.dataCache.factoryShare",
        "domain.dataCache.staleShare",
        "domain.dataCache.stale",
        "domain.dataCache.hits",
        "domain.dataCache.misses",
        "domain.dataCache.factoryRuns",
        "domain.dataCache.factoryFailures",
        "domain.dataCache.factoryFailureRate",
        "domain.impact.factoryAvoidance",
        "domain.impact.factoryShare",
        "domain.impact.avgFactoryDurationMs",
        "domain.impact.estFactoryTimeSavedMs",
        "domain.impact.timeSavedRatio",
        "domain.impact.benefit",
        "domain.impact.candidate",
        "domain.impact.lowRequestSample",
        "domain.impact.lowDurationSample",
        "domain.instanceSpread.outputCacheHitShare.stdev",
        "domain.instanceSpread.outputCacheHitShare.sampleCount",
        "domain.instanceSpread.factoryShare.stdev",
        "domain.instanceSpread.factoryShare.sampleCount",
        "endpoint.route",
        "endpoint.requests",
        "endpoint.configuredDomain",
        "endpoint.factoryFailureRate",
        "endpoint.outputCache.hitShare",
        "endpoint.dataCache.hitShare",
        "endpoint.dataCache.factoryShare",
        "endpoint.dataCache.staleShare",
        "endpoint.dataCache.stale",
        "endpoint.dataCache.factoryRuns",
        "endpoint.dataCache.factoryFailures",
        "endpoint.dataCache.factoryFailureRate",
        "endpoint.impact.factoryAvoidance",
        "endpoint.impact.factoryShare",
        "endpoint.impact.avgFactoryDurationMs",
        "endpoint.impact.estFactoryTimeSavedMs",
        "endpoint.impact.timeSavedRatio",
        "endpoint.impact.benefit",
        "endpoint.impact.candidate",
        "endpoint.impact.lowRequestSample",
        "endpoint.impact.lowDurationSample",
        "endpoint.instanceSpread.factoryShare.stdev",
        "endpoint.instanceSpread.factoryShare.sampleCount",
        "config.outputCacheTtlSeconds",
        "config.dataCacheTtlSeconds",
        "config.hardTtlSeconds",
        "config.failSafeSeconds",
        "config.clientTtlSeconds",
        "config.clientTtlMinSeconds",
        "config.schedulePhase",
        "config.scheduledUpdateUtc",
        "config.versionIsRuntimeOverride",
        "config.hasSchedule",
        "config.holdAgeHours",
        "config.clientTtlOverOutputRatio",
        "config.clientTtlCannotRamp",
        "config.fusionHardLtSoft",
        "config.dataCacheHardLtSoft",
        "config.dataCacheInstanceName",
    };

    public static bool IsKnown(string path) => Paths.Contains(path.Trim());

    public static IReadOnlyCollection<string> All => Paths;
}
